info:
  name: Create MS Teams config
  type: http
  seq: 10

http:
  method: POST
  url: "{{baseUrl}}/config"
  body:
    type: json
    data: |-
      {
        "identifier": "msteams",
        "validate": true,
        "signature": {
          "encoding": "base64",
          "algorithm": "sha256",
          "header": "Authorization",
          "template": "hash({body})"
        },
        "secret": {
          "encoding": "base64",
          "value": "{{$randomPassword}}"
        }
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
