apm-server:
  host: "0.0.0.0:9400"
  auth:
    api_key:
      enabled: 
      #limit: 100
    secret_token: "lab-secret-apm-client"
    anonymous:
      enabled: true
#================================ Outputs =================================
#-------------------------- Elasticsearch output --------------------------
output.elasticsearch:
  hosts: ["http://elastic-search:9200"]
  enabled: true
  #path: "/elasticsearch"
  #compression_level: 0
  #protocol: "https"
  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  #username: "apm_system"
  #password: "APM_P@ssw0rd"
  username: "elastic"
  password: "my-elastic-password"
#----------------------------- Console output -----------------------------
#output.console:
  #enabled: false
  #codec.json:
    #pretty: false
    #escape_html: false
#============================= Instrumentation =============================
instrumentation:
  enabled: false
#================================= Logging =================================
#logging.level: info
#logging.selectors: [ ]
logging.to_syslog: true
#logging.metrics.enabled: false
#logging.metrics.period: 30s
#logging.to_files: true
#logging.files:
  #path: /var/log/apm-server
  #name: apm-server
  #rotateeverybytes: 10485760 # = 10MB
  #keepfiles: 7
  #permissions: 0600
  #interval: 0

