metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ${ELASTIC_HOST}
  #ssl.certificate_authorities: "certs/ca/ca.crt"
  #ssl.certificate: "certs/es01/es01.crt"
  #ssl.key: "certs/es01/es01.key"
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: false
- module: logstash
  xpack.enabled: true
  period: 10s
  hosts: ${LOGSTASH_HOST}
- module: kibana
  metricsets:
  - stats
    period: 10s
    hosts: ${KIBANA_HOST}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    xpack.enabled: true
- module: docker
  metricsets:
   - "container"
   - "cpu"
   - "diskio"
   - "healthcheck"
   - "info"
   #- "image"
   - "memory"
   - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
processors:
- add_host_metadata: ~
- add_docker_metadata: ~
output.elasticsearch:
  hosts: ${ELASTIC_HOST}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  #ssl:
  #certificate: "certs/es01/es01.crt"
    #certificate_authorities: "certs/ca/ca.crt"
    #key: "certs/es01/es01.key"
