[tools]
usage = "3.2.0"

# languages
rust = "latest"
node = "lts"
deno = "latest"
bun = "latest"
python = { version = "3.12", postinstall = "pip install pipx" }

# .NET
"dotnet:aspire.cli" = "latest"
"dotnet:apache.avro.tools" = "1.12.1"
"dotnet:csharprepl" = "latest"
"dotnet:dotnet-ef" = "8"
"dotnet:yuniql.cli" = "latest"
"dotnet:dotnet-reportgenerator-globaltool" = "latest"

# AI
opencode = "latest"

# shell
powershell = "latest"
lsd = "latest"
ripgrep = "latest"
yq = "latest"
"cargo:bat" = "latest"
"cargo:git-delta" = "latest"
fd = "latest"
fzf = "latest"

# editor
neovim = "latest"

# cloud
"pipx:azure-cli" = "latest"
lazygit = "latest"
"cargo:viddy" = "latest"

[settings]
experimental = true
