[tools]
usage = "3.2.0"

# languages
rust = "latest"
cargo-binstall = "latest"
go = "latest"
node = "lts"
deno = "latest"
bun = "latest"
python = { version = "3.12", postinstall = "pip install pipx" }

# .NET
"dotnet:aspire.cli" = "latest"
"dotnet:apache.avro.tools" = "1.12.1"
"dotnet:csharprepl" = "latest"
"dotnet:dotnet-ef" = "8"
"dotnet:yuniql.cli" = "latest"
"dotnet:dotnet-reportgenerator-globaltool" = "latest"

# AI
opencode = "latest"
"npm:@github/copilot" = "latest"
claude-code = "latest"
gemini-cli = "latest"

# shell
powershell = "latest"
lsd = "latest" # ls alternative
ripgrep = "latest" # grep alternative
yq = "latest" # jq with yaml support
"cargo:bat" = { version = "latest", depends = "rust" } # cat alternative
"cargo:git-delta" = { version = "latest", depends = "rust" } # diff viewer
fd = "latest" # find alternative
fzf = "latest"
"cargo:viddy" = { version = "latest", depends = "rust" } # watch alternative
"cargo:rgx-cli" = {
    version = "latest",
    depends = "rust",
    features = "pcre2-engine",
    postinstall = "rgx --completions zsh > {{ get_env(name='HOME', default='') }}/.local/share/zsh/completion/_rgx"
} # regex helper
"cargo:darya" = { version = "latest", depends = "rust" } # disk usage analysis
"github:facebook/zstd" = {
    version = "latest",
    asset_pattern = "zstd-{{ version }}.tar.gz",
    bin_path = "zstd-{{ version }}/programs",
    filter_bins = "zstdless,zstdgrep",
    postinstall = '''
        target_dir="$MISE_TOOL_INSTALL_PATH/zstd-$MISE_TOOL_VERSION"
        make -C "$target_dir"
        ln -sv "$target_dir/programs/zstd" "$MISE_TOOL_INSTALL_PATH/.mise-bins"
    '''
}

# software development
neovim = "latest"
lazygit = "latest" # GIT client
"github:cube2222/octosql" = "latest" # explore csv, yaml, json using SQL query or event DB

# cloud
"pipx:azure-cli" = { version = "latest", depends = "python" }
"cargo:csvlens" = "latest"

[settings]
experimental = true

[settings.cargo]
binstall = true
