name: persistent

services:
  db-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db.mssql
    hostname: mssql
    labels:
      - dev.orbstack.domains=mssql.${DOMAIN}
    ports:
      - "1433:1433"
    healthcheck:
      test: >
        bash -c '$(find /opt -name sqlcmd) -S localhost -C -U sa -P "$$MSSQL_SA_PASSWORD" -Q "select 1"'
      interval: 10s
      timeout: 3s
      retries: 2
    restart: unless-stopped
    volumes:
      - mssqldata:/var/opt/mssql
    profiles: [sql]
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
      MSSQL_MEMORY_LIMIT_MB: 4096
      MSSQL_AGENT_ENABLED: true
      TZ: ${TZ}

  db-postgre:
    image: postgres
    container_name: db.postgre
    hostname: postgre
    restart: unless-stopped
    shm_size: 2gb
    labels:
      - dev.orbstack.domains=postgre.${DOMAIN}
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -h localhost -p 5432
      interval: 10s
      timeout: 3s
      retries: 2
    profiles: [sql]
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgredata:/var/lib/postgresql/data

  nosql-mongo:
    image: mongo
    container_name: db.mongo
    hostname: mongo
    labels:
      - dev.orbstack.domains=mongo.${DOMAIN}
    restart: unless-stopped
    profiles: [nosql]
    environment:
      TZ: ${TZ}
      TIME_ZONE: ${TZ}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27017:27017
    healthcheck:
      test: >
        bash -c 'mongosh -u $$MONGO_INITDB_ROOT_USERNAME -p '$$MONGO_INITDB_ROOT_PASSWORD' --port 27017 --authenticationDatabase admin --eval "db.runCommand({ ping: 1})" | grep ok'
      interval: 10s
      timeout: 3s
      retries: 2
    volumes:
      - mongodata:/data/db

  nosql-cosmos:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    platform: linux/amd64
    container_name: db.cosmos
    hostname: azcosmos
    labels:
      - dev.orbstack.domains=azcosmos.${DOMAIN}
      - dev.orbstack.http-port=8081
    cpu_count: 2
    tty: true
    volumes:
      - azcosmosdata:/tmp
    ports:
      - "8083:8081"
      - "8900:8900"
      - "8901:8901"
      - "8979:8979"
      - "10250-10255:10250-10255"
    restart: unless-stopped
    profiles: [nosql]
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 4
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: true

  az-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: blob.azurite
    hostname: azurite
    labels:
      - dev.orbstack.domains=azurite.${DOMAIN}
    volumes:
      - azuritedata:/data
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    restart: unless-stopped
    command: ["azurite", "--blobHost", "0.0.0.0", "--queueHost", "0.0.0.0", "--tableHost", "0.0.0.0", "--skipApiVersionCheck"]
    profiles: [blob]

volumes:
  mssqldata:
  postgredata:
  mongodata:
  azcosmosdata:
  azuritedata:

networks:
  default:
    name: backend
    external: true
